services:
  - type: worker
    name: AutoAdultBot
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /
    startCommand: python3 -m bot
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
    autoDeploy: true
